// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechSalesManagement.Infrastructure.Persistence;

#nullable disable

namespace TechSalesManagement.Migrations
{
    [DbContext(typeof(TechSalesDbContext))]
    [Migration("20260512122930_ADD_Data4Roles")]
    partial class ADD_Data4Roles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.AuditLogDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("affected_columns")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("new_values")
                        .HasColumnType("text");

                    b.Property<string>("old_values")
                        .HasColumnType("text");

                    b.Property<string>("primary_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CartDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CartItemDbModel", b =>
                {
                    b.Property<Guid>("cart_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("cart_id", "product_id");

                    b.HasIndex("product_id");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CategoryDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.InventoryDbModel", b =>
                {
                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("reserved_quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("product_id");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.NotificationDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("is_read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ref_to")
                        .HasColumnType("uuid");

                    b.Property<string>("title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("discount_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("shipping_address_snapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("shipping_fee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("total_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("total_product_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderItemDbModel", b =>
                {
                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("order_id", "product_id");

                    b.HasIndex("product_id");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderVoucherDbModel", b =>
                {
                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("voucher_id")
                        .HasColumnType("uuid");

                    b.HasKey("order_id", "voucher_id");

                    b.HasIndex("voucher_id");

                    b.ToTable("OrderVoucher", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PaymentDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("order_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("payment_method_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("transaction_ref")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("payment_method_id");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PaymentMethodDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PermissionDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("category_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ProductImageDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_primary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.ToTable("ProductImage", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ReviewDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("product_id")
                        .HasColumnType("uuid");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ReviewResponseDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("review_id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("review_id");

                    b.HasIndex("user_id");

                    b.ToTable("ReviewResponse", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.RoleDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("668a08c6-9b2d-4189-96f9-7cc07e5a3b5a"),
                            created_at = new DateTimeOffset(new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Technical Administrator with full system access",
                            name = "Technical Admin"
                        },
                        new
                        {
                            id = new Guid("75595ed2-8e03-476c-a59c-864fbc57b1a9"),
                            created_at = new DateTimeOffset(new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Default customer access",
                            name = "Customer"
                        },
                        new
                        {
                            id = new Guid("8e2a0a54-e882-4174-ae34-32f299096d13"),
                            created_at = new DateTimeOffset(new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Sales Staff member access",
                            name = "Staff"
                        },
                        new
                        {
                            id = new Guid("c22cf7a1-67f6-479c-a3df-9504f8270fa6"),
                            created_at = new DateTimeOffset(new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            description = "Business Administrator for management tasks",
                            name = "Business Admin"
                        });
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.RolePermissionDbModel", b =>
                {
                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uuid");

                    b.HasKey("role_id", "permission_id");

                    b.HasIndex("permission_id");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ShippingAddressDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("deleted_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("ShippingAddress", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("failed_login_attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("last_failed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("locked_until")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserProfileDbModel", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<string>("avatar_url")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("user_id");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserRoleDbModel", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserTokenDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("expired_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("used_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("user_id", "type");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.VoucherDbModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("max_usage")
                        .HasColumnType("integer");

                    b.Property<decimal>("min_order_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("used_count")
                        .HasColumnType("integer");

                    b.Property<decimal>("value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.AuditLogDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("audit_logs")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CartDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithOne("cart")
                        .HasForeignKey("TechSalesManagement.Infrastructure.Persistence.Models.CartDbModel", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CartItemDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.CartDbModel", "cart")
                        .WithMany("cart_items")
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", "product")
                        .WithMany("cart_items")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.InventoryDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", "product")
                        .WithOne("inventory")
                        .HasForeignKey("TechSalesManagement.Infrastructure.Persistence.Models.InventoryDbModel", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.NotificationDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("notifications")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderItemDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", "order")
                        .WithMany("order_items")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", "product")
                        .WithMany("order_items")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderVoucherDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", "order")
                        .WithMany("order_vouchers")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.VoucherDbModel", "voucher")
                        .WithMany("order_vouchers")
                        .HasForeignKey("voucher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("voucher");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PaymentDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", "order")
                        .WithMany("payments")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.PaymentMethodDbModel", "payment_method")
                        .WithMany("payments")
                        .HasForeignKey("payment_method_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("payment_method");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.CategoryDbModel", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ProductImageDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", "product")
                        .WithMany("product_images")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ReviewDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", "product")
                        .WithMany("reviews")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ReviewResponseDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.ReviewDbModel", "review")
                        .WithMany("review_responses")
                        .HasForeignKey("review_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("review_responses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("review");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.RolePermissionDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.PermissionDbModel", "permission")
                        .WithMany("role_permissions")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.RoleDbModel", "role")
                        .WithMany("role_permissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ShippingAddressDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("shipping_addresses")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserProfileDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithOne("user_profile")
                        .HasForeignKey("TechSalesManagement.Infrastructure.Persistence.Models.UserProfileDbModel", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserRoleDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.RoleDbModel", "role")
                        .WithMany("user_roles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("user_roles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserTokenDbModel", b =>
                {
                    b.HasOne("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", "user")
                        .WithMany("user_tokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CartDbModel", b =>
                {
                    b.Navigation("cart_items");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.CategoryDbModel", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.OrderDbModel", b =>
                {
                    b.Navigation("order_items");

                    b.Navigation("order_vouchers");

                    b.Navigation("payments");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PaymentMethodDbModel", b =>
                {
                    b.Navigation("payments");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.PermissionDbModel", b =>
                {
                    b.Navigation("role_permissions");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ProductDbModel", b =>
                {
                    b.Navigation("cart_items");

                    b.Navigation("inventory");

                    b.Navigation("order_items");

                    b.Navigation("product_images");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.ReviewDbModel", b =>
                {
                    b.Navigation("review_responses");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.RoleDbModel", b =>
                {
                    b.Navigation("role_permissions");

                    b.Navigation("user_roles");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.UserDbModel", b =>
                {
                    b.Navigation("audit_logs");

                    b.Navigation("cart");

                    b.Navigation("notifications");

                    b.Navigation("orders");

                    b.Navigation("review_responses");

                    b.Navigation("reviews");

                    b.Navigation("shipping_addresses");

                    b.Navigation("user_profile");

                    b.Navigation("user_roles");

                    b.Navigation("user_tokens");
                });

            modelBuilder.Entity("TechSalesManagement.Infrastructure.Persistence.Models.VoucherDbModel", b =>
                {
                    b.Navigation("order_vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
